### ISSUE TITLE
`ProgrammingError at / relation "core_sitepreferences" does not exist` error from Django

### ISSUE THREAD

**Issue by JinIgarashi** [unicef-drp/GeoSight-OS#169]
I am following this documentation to setup GeoSight https://unicef-drp.github.io/GeoSight-OS-Documentation/developer/guide/ide-setup/#development

My computer is MacOS M2

I changed the following settings for Docker in order to be able to access to localhost:2000

- Dockerfile at deployment/docker/Dockerfile

```diff
- FROM ubuntu:20.04 AS prod
+ FROM  --platform=amd64 ubuntu:20.04 AS prod
```

```diff
- RUN apt-get update && apt-get install -y openssh-server sudo
+ RUN apt-get update && apt-get install -y openssh-server
```

- docker-compose.override.yml

```diff
    ports:
      # for django test server
-      #- "2000:8080"
+      - "2000:8080"
```

After changing the above, I can run now `make up && make dev`, and can access to `localhost:2000`. However, it shows the below error from Django. 

![image](https://github.com/unicef-drp/GeoSight-OS/assets/2639701/9faf9171-c26e-4545-9832-7cca866b3be7)

Any idea to solve this issue?

**Comment by JinIgarashi** [comment]
![image](https://github.com/unicef-drp/GeoSight-OS/assets/2639701/86b25156-33a0-44e7-bd08-055b0664951f)

Looks like geosight_worker and geosight_celery_beat are frequently restarting. Some setups are not likely done properly.

**Comment by janbur** [comment]
@meomancer  @danangmassandy  - can you please have a look at this?

**Comment by JinIgarashi** [comment]
After I update from the latest main branch, I followed new documentation, but it still fails

```
make up
docker logs -f geosight_django
```

after this command, it shows following error which is different from what documentation says. 

```
-----------------------------------------------------
STARTING DJANGO ENTRYPOINT Fri 08 Dec 2023 08:55:23 UTC
-----------------------------------------------------
npm install
npm verb cli /usr/bin/node /usr/bin/npm
npm info using npm@10.2.3
npm info using node@v20.10.0
npm verb title npm install
npm verb argv "install" "--loglevel" "verbose"
npm verb logfile logs-max:10 dir:/root/.npm/_logs/2023-12-08T08_55_23_777Z-
npm verb logfile /root/.npm/_logs/2023-12-08T08_55_23_777Z-debug-0.log
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/advisories/bulk 660ms
npm http fetch GET 200 https://registry.npmjs.org/request 8ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/nth-check 10ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/tough-cookie 10ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/xlsx 10ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/css-select 2ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/alasql 2ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/svgo 5ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/react-svg-core 5ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/react-svg-loader 2ms (cache hit)

up to date, audited 1793 packages in 2s

443 packages are looking for funding
  run `npm fund` for details

9 vulnerabilities (2 moderate, 7 high)

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
npm verb exit 0
npm info ok 
npm build

> geo-sight-dashboard@0.0.1 build
> webpack --mode production


Killed
```

**Comment by iferencik** [comment]
@meomancer i am running on ubuntu and  managed to deploy locally GeoSight + connected to production GeoRepo as the staging did not work.

**Comment by meomancer** [comment]
hi @iferencik 
How do you know it is not connected?
Could you screenshot:
1. Your site preferences for GeoRepo?
2. The indicator that you are not connected?

**Comment by iferencik** [comment]
@meomancer 
sorry for delayed reply i was caught in 3 calls

with staging i got a red error button saying GeoRepo is not accessible
I read the email where you notified Jan the staging key has no access to DB so this must be it

**Comment by iferencik** [comment]
i tried staging url and key and  can't get it up and running

![image](https://github.com/unicef-drp/GeoSight-OS/assets/92793531/c5ff0301-6137-4af3-b4c3-c5ea20855480)

**Comment by JinIgarashi** [comment]
After I did the following instruction from Irwan, setups everything works fine (looks like), but still localhost:2000 will not be available. 

```
1. `make down`
2. `make frontend-dev`
3. Add this line after this : [https://github.com/unicef-drp/GeoSight-OS/blob/main/deployment/docker-compose.override.template.yml#L32](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Funicef-drp%2FGeoSight-OS%2Fblob%2Fmain%2Fdeployment%2Fdocker-compose.override.template.yml%23L32&data=05%7C01%7Cjin.igarashi%40undp.org%7C0a76aa43cd4a4913f38208dbf7d1a82a%7Cb3e5db5e2944483799f57488ace54319%7C0%7C0%7C638376252088224545%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=IpF5QKIt1Np4dUk5SIsQcHfjAdZ4kLiX2V5wFmyhIlk%3D&reserved=0)
    entrypoint: [ ]
    it will skip npm building
Selection_005.png
4. `make up`
5. `make shell`
6. `python -u initialize.py`
7. When it is done
8. `exit`
9. `make dev`
```

also, I saw the following warnings after `make up`.

```
 ✔ Container geosight_celery_beat                                                                                                                             Started0.0s  worker The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested           0.0s 
 ✔ Container geosight_django                                                                                                                                  Started0.0s 
 ! celery_beat The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested      0.0s 
 ! django The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested           0.0s 
 ✔ Container geosight_worker                                                                                                                                  Started0.0s 
 ✔ Container geosight_dev                                                                                                                                     Started0.0s 
 ! worker The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested           0.0s 
 ! dev The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested              0.0s 
```

I also found the following error log at geosight_dev container.

```
2023-12-08 12:09:28 Watching for file changes with StatReloader
2023-12-08 12:09:28 django.utils.autoreload INFO autoreload.py L637: Watching for file changes with StatReloader
2023-12-08 12:09:29 Exception in thread django-main-thread:
2023-12-08 12:09:29 Traceback (most recent call last):
2023-12-08 12:09:29   File "/usr/local/lib/python3.8/dist-packages/django/db/backends/base/base.py", line 219, in ensure_connection
2023-12-08 12:09:29     self.connect()
2023-12-08 12:09:29   File "/usr/local/lib/python3.8/dist-packages/django/utils/asyncio.py", line 33, in inner
2023-12-08 12:09:29     return func(*args, **kwargs)
2023-12-08 12:09:29   File "/usr/local/lib/python3.8/dist-packages/django/db/backends/base/base.py", line 200, in connect
2023-12-08 12:09:29     self.connection = self.get_new_connection(conn_params)
2023-12-08 12:09:29   File "/usr/local/lib/python3.8/dist-packages/django/utils/asyncio.py", line 33, in inner
2023-12-08 12:09:29     return func(*args, **kwargs)
2023-12-08 12:09:29   File "/usr/local/lib/python3.8/dist-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
2023-12-08 12:09:29     connection = Database.connect(**conn_params)
2023-12-08 12:09:29   File "/usr/local/lib/python3.8/dist-packages/psycopg2/__init__.py", line 122, in connect
2023-12-08 12:09:29     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
2023-12-08 12:09:29 psycopg2.OperationalError: connection to server at "db" (172.23.0.2), port 5432 failed: Connection refused
2023-12-08 12:09:29 Is the server running on that host and accepting TCP/IP connections?
2023-12-08 12:09:29 
2023-12-08 12:09:29 
2023-12-08 12:09:29 The above exception was the direct cause of the following exception:
2023-12-08 12:09:29 
2023-12-08 12:09:29 Traceback (most recent call last):
2023-12-08 12:09:29   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
2023-12-08 12:09:29     self.run()
2023-12-08 12:09:29   File "/usr/lib/python3.8/threading.py", line 870, in run
2023-12-08 12:09:29     self._target(*self._args, **self._kwargs)
2023-12-08 12:09:29   File "/usr/local/lib/python3.8/dist-packages/django/utils/autoreload.py", line 64, in wrapper
2023-12-08 12:09:29     fn(*args, **kwargs)
2023-12-08 12:09:29   File "/usr/local/lib/python3.8/dist-packages/django/core/management/commands/runserver.py", line 121, in inner_run
2023-12-08 12:09:29     self.check_migrations()
2023-12-08 12:09:29   File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 486, in check_migrations
2023-12-08 12:09:29     executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
2023-12-08 12:09:29   File "/usr/local/lib/python3.8/dist-packages/django/db/migrations/executor.py", line 18, in __init__
2023-12-08 12:09:29     self.loader = MigrationLoader(self.connection)
2023-12-08 12:09:29   File "/usr/local/lib/python3.8/dist-packages/django/db/migrations/loader.py", line 53, in __init__
2023-12-08 12:09:29     self.build_graph()
2023-12-08 12:09:29   File "/usr/local/lib/python3.8/dist-packages/django/db/migrations/loader.py", line 220, in build_graph
2023-12-08 12:09:29     self.applied_migrations = recorder.applied_migrations()
2023-12-08 12:09:29   File "/usr/local/lib/python3.8/dist-packages/django/db/migrations/recorder.py", line 77, in applied_migrations
2023-12-08 12:09:29     if self.has_table():
2023-12-08 12:09:29   File "/usr/local/lib/python3.8/dist-packages/django/db/migrations/recorder.py", line 55, in has_table
2023-12-08 12:09:29     with self.connection.cursor() as cursor:
2023-12-08 12:09:29   File "/usr/local/lib/python3.8/dist-packages/django/utils/asyncio.py", line 33, in inner
2023-12-08 12:09:29     return func(*args, **kwargs)
2023-12-08 12:09:29   File "/usr/local/lib/python3.8/dist-packages/django/db/backends/base/base.py", line 259, in cursor
2023-12-08 12:09:29     return self._cursor()
2023-12-08 12:09:29   File "/usr/local/lib/python3.8/dist-packages/django/db/backends/base/base.py", line 235, in _cursor
2023-12-08 12:09:29     self.ensure_connection()
2023-12-08 12:09:29   File "/usr/local/lib/python3.8/dist-packages/django/utils/asyncio.py", line 33, in inner
2023-12-08 12:09:29     return func(*args, **kwargs)
2023-12-08 12:09:29   File "/usr/local/lib/python3.8/dist-packages/django/db/backends/base/base.py", line 219, in ensure_connection
2023-12-08 12:09:29     self.connect()
2023-12-08 12:09:29   File "/usr/local/lib/python3.8/dist-packages/django/db/utils.py", line 90, in __exit__
2023-12-08 12:09:29     raise dj_exc_value.with_traceback(traceback) from exc_value
2023-12-08 12:09:29   File "/usr/local/lib/python3.8/dist-packages/django/db/backends/base/base.py", line 219, in ensure_connection
2023-12-08 12:09:29     self.connect()
2023-12-08 12:09:29   File "/usr/local/lib/python3.8/dist-packages/django/utils/asyncio.py", line 33, in inner
2023-12-08 12:09:29     return func(*args, **kwargs)
2023-12-08 12:09:29   File "/usr/local/lib/python3.8/dist-packages/django/db/backends/base/base.py", line 200, in connect
2023-12-08 12:09:29     self.connection = self.get_new_connection(conn_params)
2023-12-08 12:09:29   File "/usr/local/lib/python3.8/dist-packages/django/utils/asyncio.py", line 33, in inner
2023-12-08 12:09:29     return func(*args, **kwargs)
2023-12-08 12:09:29   File "/usr/local/lib/python3.8/dist-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
2023-12-08 12:09:29     connection = Database.connect(**conn_params)
2023-12-08 12:09:29   File "/usr/local/lib/python3.8/dist-packages/psycopg2/__init__.py", line 122, in connect
2023-12-08 12:09:29     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
2023-12-08 12:09:29 django.db.utils.OperationalError: connection to server at "db" (172.23.0.2), port 5432 failed: Connection refused
2023-12-08 12:09:29 Is the server running on that host and accepting TCP/IP connections?
2023-12-08 12:09:29 
```

**Comment by meomancer** [comment]
Hi @JinIgarashi 
Could you do
`docker rm -f geosight_dev`
`make up`

It seems the db is not up yet, but dev is already up
I will fix it next week
But could you do above please?

**Comment by JinIgarashi** [comment]
@meomancer Thanks. After doing the above commands, it works now.

<img width="761" alt="image" src="https://github.com/unicef-drp/GeoSight-OS/assets/2639701/4b4ed672-7f4b-439a-b3fe-79c5d16e5ffd">

**Comment by meomancer** [comment]
Great, thank you @JinIgarashi 
I will fix this deployment next week
But for current fix, please do above

**Comment by JinIgarashi** [comment]
I needed to run `make devweb-load-demo-data` to load demo project.

Now it can see

<img width="761" alt="image" src="https://github.com/unicef-drp/GeoSight-OS/assets/2639701/6cec71be-05b7-4cc8-b6fe-f92f44a640d3">

**Comment by JinIgarashi** [comment]
@meomancer 

I also needed to change Dockerfiles like below

```diff
- RUN apt update
- RUN apt-get install chromium-browser -y
+ RUN apt-get update
+ RUN apt-get install chromium-browser -y --fix-missing
```

Also, `docker-compose.override.yml`, 2000 port can be accessed

```diff
    ports:
      # for django test server
-     # - "2000:8080"
+     - "2000:8080"
```

probably you need to fix these

**Comment by meomancer** [comment]
Thank you @JinIgarashi  for suggestion
For the Dockerfile i think we can update thet
For the override.yml, we can't uncomment it, because it will conflict with vscode deployment

I will update the document about this port
Basically this port needs to be opened if we don't run using vscode (run using make dev)

Could you create PR for just the Dockerfile?

**Comment by JinIgarashi** [comment]
let me create a PR for Dockerfile

**Comment by meomancer** [comment]
We could close this for now
